version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cdp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cdp-network

  # Customer Data Platform Application
  app:
    image: cdp-app:latest
    container_name: cdp-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - cdp-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  cdp-network:
    driver: bridge