version: '3.8'

services:
  # Customer Data Platform Application
  cdp-app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: cdp-platform-local
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000
      - HOST=0.0.0.0
      - SESSION_SECRET=${SESSION_SECRET:-default-secret-change-this}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - cdp-network

  # Redis for job queues and caching
  redis:
    image: redis:7-alpine
    container_name: cdp-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - cdp-network

volumes:
  redis_data:
    driver: local

networks:
  cdp-network:
    driver: bridge 